### ISSUE TITLE
TypeError: Missing required parameter digestmod

### ISSUE THREAD

**Issue by teleprint-me** [dagnelies/canister#14]
**Context**
I'm setting up a Local Server using Ubuntu 20.04.1 LTS in a Virtual Machine. I installed and configured Apache2, MySQL, and Python3. This includes all dependencies. I can run Bottle and Jinja2 through WSGI successfully.

**Problem**
My main.py source file triggers a trace back error with a message consisting of `TypeError: Missing required parameter 'digestmod'.`. This error _only_ appears when I'm using Canister.

**Apache2 Error Log**
```python
==> /var/log/apache2/error.log <==
[Wed Jan 20 22:23:21.231429 2021] [mpm_event:notice] [pid 7189:tid 140411060796480] AH00491: caught SIGTERM, shutting down
[Wed Jan 20 22:23:21.330978 2021] [mpm_event:notice] [pid 7948:tid 139828615461952] AH00489: Apache/2.4.41 (Ubuntu) mod_wsgi/4.6.8 Python/3.8 configured -- resuming normal operations
[Wed Jan 20 22:23:21.331071 2021] [core:notice] [pid 7948:tid 139828615461952] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 20 22:24:08.287914 2021] [wsgi:info] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268] mod_wsgi (pid=7949, process='teletype', application=''): Loading Python script file '/home/morgan/teletype/teletype/main.py'.
[Wed Jan 20 22:24:08.372935 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,372 INFO     [MainThread]   ============
[Wed Jan 20 22:24:08.373008 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,372 INFO     [MainThread]   Initializing
[Wed Jan 20 22:24:08.373047 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,373 INFO     [MainThread]   ============
[Wed Jan 20 22:24:08.373087 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,373 INFO     [MainThread]   python version: 3.8.5 (default, Jul 28 2020, 12:59:40) 
[Wed Jan 20 22:24:08.373094 2021] [wsgi:error] [pid 7949:tid 139828502984448] [GCC 9.3.0]
[Wed Jan 20 22:24:08.373124 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,373 INFO     [MainThread]   bottle version: 0.12.15
[Wed Jan 20 22:24:08.373484 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,373 INFO     [MainThread]   ------------------------------------------
[Wed Jan 20 22:24:08.373524 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,373 INFO     [MainThread]   catchall                       = True
[Wed Jan 20 22:24:08.373558 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,373 INFO     [MainThread]   autojson                       = True
[Wed Jan 20 22:24:08.373597 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,373 INFO     [MainThread]   canister.auth_basic_username   = morgan
[Wed Jan 20 22:24:08.373645 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,373 INFO     [MainThread]   canister.auth_basic_encryption = clear
[Wed Jan 20 22:24:08.373775 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,373 INFO     [MainThread]   canister.auth_basic_password   = my-secret
[Wed Jan 20 22:24:08.373934 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,373 INFO     [MainThread]   ------------------------------------------
[Wed Jan 20 22:24:08.374117 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,374 INFO     [MainThread]   Session timeout is 3600 seconds. Checking for expired sessions every 60 seconds. 
[Wed Jan 20 22:24:08.374364 2021] [wsgi:error] [pid 7949:tid 139828502984448] 2021-01-20 22:24:08,374 INFO     [MainThread]   Basic authentication enabled.
[Wed Jan 20 22:24:08.375176 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268] 2021-01-20 22:24:08,375 INFO     [x.x.x.x-...]   GET http://x.x.x.x/
[Wed Jan 20 22:24:08.376153 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268] Traceback (most recent call last):
[Wed Jan 20 22:24:08.376171 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]   File "/usr/lib/python3/dist-packages/bottle.py", line 862, in _handle
[Wed Jan 20 22:24:08.376175 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]     return route.call(**args)
[Wed Jan 20 22:24:08.376178 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]   File "/usr/lib/python3/dist-packages/bottle.py", line 1740, in wrapper
[Wed Jan 20 22:24:08.376181 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]     rv = callback(*a, **ka)
[Wed Jan 20 22:24:08.376184 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]   File "/usr/local/lib/python3.8/dist-packages/canister.py", line 280, in wrapper
[Wed Jan 20 22:24:08.376186 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]     res.set_cookie('session_id', sid, secret=self.session_secret)
[Wed Jan 20 22:24:08.376189 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]   File "/usr/lib/python3/dist-packages/bottle.py", line 1624, in set_cookie
[Wed Jan 20 22:24:08.376192 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]     value = touni(cookie_encode((name, value), secret))
[Wed Jan 20 22:24:08.376195 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]   File "/usr/lib/python3/dist-packages/bottle.py", line 2598, in cookie_encode
[Wed Jan 20 22:24:08.376197 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]     sig = base64.b64encode(hmac.new(tob(key), msg).digest())
[Wed Jan 20 22:24:08.376200 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]   File "/usr/lib/python3.8/hmac.py", line 153, in new
[Wed Jan 20 22:24:08.376203 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]     return HMAC(key, msg, digestmod)
[Wed Jan 20 22:24:08.376206 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]   File "/usr/lib/python3.8/hmac.py", line 51, in __init__
[Wed Jan 20 22:24:08.376208 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268]     raise TypeError("Missing required parameter 'digestmod'.")
[Wed Jan 20 22:24:08.376251 2021] [wsgi:error] [pid 7949:tid 139828502984448] [remote x.x.x.x:60268] TypeError: Missing required parameter 'digestmod'.
```

**main.py**
```python
   17 import sys                                                                                                              
   18 import os                                                                                                               
   19                                                                                                                         
   20 # change working dir so relative paths are registered                                                                   
   21 os.chdir(os.path.dirname(__file__))                                                                                     
   22 sys.path.append(os.path.dirname(__file__))                                                                              
   23                                                                                                                         
   24 from src.jinja import render                                                                                            
   25 from src.sql import SQL                                                                                                 
   26                                                                                                                         
   27 import bottle                                                                                                           
   28 import canister                                                                                                         
   29                                                                                                                         
   30 tty = bottle.Bottle()                                                                                                   
   31 tty.config.load_config('./config/canister.conf')                                                                        
   32 tty.install(canister.Canister())                                                                                        
   33                                                                                                                         
   34                                                                                                                         
   35 #                                                                                                                       
   36 # Set Static Path                                                                                                       
   37 #                                                                                                                       
   38 @tty.route('/static/<filepath:path>', name='static')                                                                    
   39 def static(filepath):                                                                                                   
   40     return bottle.static_file(filepath, root='static')                                                                  
   41                                                                                                                         
   42                                                                                                                         
   43 #                                                                                                                       
   44 # Dummy route                                                                                                           
   45 #                                                                                                                       
   46 @tty.route('/')                                                                                                         
   47 def index():                                                                                                            
   48     return render('index.html')                                                                                         
   49                                                                                                                         
   50                                                                                                                         
   51 application = tty  
```

**NOTE**:
[`inspect.getargspec`](https://docs.python.org/3/library/inspect.html#inspect.getargspec) is deprecated. this is _only_ triggered when running Bottle locally. The warning seems to disappear when running it on Bottle through Apache2 and WSGI.

>Deprecated since version 3.0: Use getfullargspec() for an updated API that is usually a drop-in replacement, but also correctly handles function annotations and keyword-only parameters.

If I find a solution in the mean time, then I'll fork and make a pull request or just post the solution if it turns out to be related to something else triggering the error. It seems like it is directly related to the Canister plugin so far.

**Comment by teleprint-me** [comment]
The issue was due to using an outdated package version of `python3-bottle`. Running `sudo apt-get install python3-bottle` installs `v0.12.15` which causes the error. I removed the system package after comparing versioning to pypi's Bottle package. I then installed the latest v0.12.19 using `sudo -H pip3 install -U bottle`. A quick reboot and the issue resolved it self. So error was not due solely to the plugin; mostly due to user error.

**Apache2 Error Log**
```
[Thu Jan 21 02:23:29.066513 2021] [mpm_event:notice] [pid 10714:tid 139806349085760] AH00491: caught SIGTERM, shutting down
[Thu Jan 21 02:23:46.789840 2021] [mpm_event:notice] [pid 888:tid 140587606596672] AH00489: Apache/2.4.41 (Ubuntu) mod_wsgi/4.6.8 Python/3.8 configured -- resuming normal operations
[Thu Jan 21 02:23:46.798392 2021] [core:notice] [pid 888:tid 140587606596672] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jan 21 02:25:00.105786 2021] [wsgi:info] [pid 889:tid 140587460540160] [remote x.x.x.x:35402] mod_wsgi (pid=889, process='teletype', application=''): Loading Python script file '/home/morgan/teletype/teletype/main.py'.
[Thu Jan 21 02:25:00.220768 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,220 INFO     [MainThread]   ============
[Thu Jan 21 02:25:00.220872 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,220 INFO     [MainThread]   Initializing
[Thu Jan 21 02:25:00.220939 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,220 INFO     [MainThread]   ============
[Thu Jan 21 02:25:00.220985 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,220 INFO     [MainThread]   python version: 3.8.5 (default, Jul 28 2020, 12:59:40) 
[Thu Jan 21 02:25:00.220992 2021] [wsgi:error] [pid 889:tid 140587460540160] [GCC 9.3.0]
[Thu Jan 21 02:25:00.221044 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,221 INFO     [MainThread]   bottle version: 0.12.19
[Thu Jan 21 02:25:00.221111 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,221 INFO     [MainThread]   ------------------------------------------
[Thu Jan 21 02:25:00.221153 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,221 INFO     [MainThread]   catchall                       = True
[Thu Jan 21 02:25:00.221209 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,221 INFO     [MainThread]   autojson                       = True
[Thu Jan 21 02:25:00.221266 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,221 INFO     [MainThread]   canister.auth_basic_username   = morgan
[Thu Jan 21 02:25:00.221307 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,221 INFO     [MainThread]   canister.auth_basic_encryption = sha256
[Thu Jan 21 02:25:00.221358 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,221 INFO     [MainThread]   canister.auth_basic_password   = my-secret
[Thu Jan 21 02:25:00.221402 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,221 INFO     [MainThread]   ------------------------------------------
[Thu Jan 21 02:25:00.221470 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,221 INFO     [MainThread]   Session timeout is 3600 seconds. Checking for expired sessions every 60 seconds. 
[Thu Jan 21 02:25:00.221689 2021] [wsgi:error] [pid 889:tid 140587460540160] 2021-01-21 02:25:00,221 INFO     [MainThread]   Basic authentication enabled.
[Thu Jan 21 02:25:00.222373 2021] [wsgi:error] [pid 889:tid 140587460540160] [remote x.x.x.x:35402] 2021-01-21 02:25:00,222 INFO     [x.x.x.x-...]   GET http://x.x.x.x/
[Thu Jan 21 02:25:00.222568 2021] [wsgi:error] [pid 889:tid 140587460540160] [remote x.x.x.x:35402] 2021-01-21 02:25:00,222 INFO     [x.x.x.x-...]   Session created: Ym70sMucOafpbUVnx57/YTGG
[Thu Jan 21 02:25:00.226314 2021] [wsgi:error] [pid 889:tid 140587460540160] [remote x.x.x.x:35402] 2021-01-21 02:25:00,226 INFO     [x.x.x.x-Ym70sM]   Response: 200 (3ms)
```

Follow up requests also gives the desired result

```
[Thu Jan 21 02:25:00.264929 2021] [wsgi:error] [pid 889:tid 140587578046208] [remote x.x.x.x:35402] 2021-01-21 02:25:00,264 INFO     [x.x.x.x-...]   GET http://x.x.x.x/static/styles/normalize.css
[Thu Jan 21 02:25:00.266083 2021] [wsgi:error] [pid 889:tid 140587578046208] [remote x.x.x.x:35402] 2021-01-21 02:25:00,266 INFO     [x.x.x.x-...]   Session found: Ym70sMucOafpbUVnx57/YTGG
[Thu Jan 21 02:25:00.269019 2021] [wsgi:error] [pid 889:tid 140587578046208] [remote x.x.x.x:35402] 2021-01-21 02:25:00,268 INFO     [x.x.x.x-Ym70sM]   Response: 200 (4ms)
```
